### ISSUE TITLE
Infografia Ciclo de vida del desarrollo de software

### ISSUE THREAD

**Issue by Luz1727** [SistemasTecTlaxiaco/actividad-1-infografia-Luz1727#2]
[InfografiaUNIDAD1-LuzArlethLB.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Luz1727/files/12491750/InfografiaUNIDAD1-LuzArlethLB.pdf).

**Comment by yanet02** [comment]
Redacción y ortografía:  "EXCELENTE" 3 puntos de 3 puntos
Exposición de ideas centrales: BUEN TRABAJO 3 puntos de 3 puntos
Organización de la información: BUENA ORGANIZACION 3 puntos de 3 puntos
Uso de imágenes y colores: UNA BUENA REPRESENTACION 3 puntos de 3 puntos
Presentación visual: MUY BUENA 3 puntos de 3 puntos
Referencias: 2 puntos de 2 puntos
Presentación: 3 puntos de 3 puntos

Calificación: 20 / 20
Calificado por: Yanet Gonzalez

**Comment by josealfredo79** [comment]
Bien echo y revisado..
